[package]
name = "pizzarust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_asset_loader = "0.11"
image = "0.23.14"
rand = "0.8"
